/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java02_cp17310;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUYVU
 */
public class StudentManagement extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    List<Student> listStudent = new ArrayList<>();

    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
        tableModel = (DefaultTableModel) tblListStudent.getModel();
        getComboBoxModelClassName();
        getFakeDataTable();
    }
    
    public void getComboBoxModelClassName() {
        // B1: Tao danh sach
        List<String> classNames = new ArrayList<>();
        classNames.add("CP17310");
        classNames.add("CP17308");
        classNames.add("CP17225");
        
        // B2: Duyet danh sach va them vao comboBoxModel
        for (String name : classNames) {
            comboBoxModel.addElement(name);
        }
        
        // B3: Set comboBoxModel cho cboClassName
        cboClassName.setModel(comboBoxModel);
    } 
    public void getFakeDataTable() {
        Student student1 = new Student();
        student1.setStudentNo("PH02575");
        student1.setStudentName("Vu Thi Thuy");
        student1.setGender("Nu");
        student1.setClassName("CP17308");
        student1.setFinalGrade(7.5);
        student1.setStatus(true);
        
        Student student2 = new Student();
        student2.setStudentNo("PH02733");
        student2.setStudentName("Nguyen Van Luong");
        student2.setGender("Nam");
        student2.setClassName("CP17308");
        student2.setFinalGrade(8.5);
        student2.setStatus(true);
        
        // THEM DOI TUONG VAO DANH SACH
        listStudent.add(student1);
        listStudent.add(student2);
        
        for (Student std : listStudent) {
            tableModel.addRow(new Object[] {std.getStudentNo(), std.getStudentName(),
                std.getGender(), std.getYob(), std.getClassName(), std.getFinalGrade(),
                std.getNotes(), std.isStatus()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tpnUpdateStudent = new javax.swing.JTabbedPane();
        pbList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListStudent = new javax.swing.JTable();
        pnUpdate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        txtYOB = new javax.swing.JTextField();
        cboClassName = new javax.swing.JComboBox<>();
        txtFinalGrade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        chkStatus = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manage Student");

        tblListStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "Gender", "YOB", "Class Name", "Final Grade", "Notes", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListStudent);

        javax.swing.GroupLayout pbListLayout = new javax.swing.GroupLayout(pbList);
        pbList.setLayout(pbListLayout);
        pbListLayout.setHorizontalGroup(
            pbListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        pbListLayout.setVerticalGroup(
            pbListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        tpnUpdateStudent.addTab("List", pbList);

        jLabel2.setText("Student Number");

        jLabel3.setText("Student Name");

        jLabel4.setText("Gender");

        jLabel5.setText("Year Of Birth");

        jLabel6.setText("Class");

        jLabel7.setText("Final grade");

        jLabel8.setText("Notes");

        jLabel9.setText("Status");

        buttonGroup1.add(rdoMale);
        rdoMale.setSelected(true);
        rdoMale.setText("Male");

        buttonGroup1.add(rdoFemale);
        rdoFemale.setText("Female");

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        chkStatus.setText("Graduated ?");

        javax.swing.GroupLayout pnUpdateLayout = new javax.swing.GroupLayout(pnUpdate);
        pnUpdate.setLayout(pnUpdateLayout);
        pnUpdateLayout.setHorizontalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStudentNo)
                            .addComponent(txtStudentName)
                            .addGroup(pnUpdateLayout.createSequentialGroup()
                                .addComponent(rdoMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                                .addComponent(rdoFemale))
                            .addComponent(txtYOB)
                            .addComponent(cboClassName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFinalGrade)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnUpdateLayout.setVerticalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoMale)
                    .addComponent(rdoFemale))
                .addGap(24, 24, 24)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtYOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFinalGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkStatus)))
                .addContainerGap())
        );

        tpnUpdateStudent.addTab("Update", pnUpdate);

        btnReset.setText("Reset");

        btnAddNew.setText("Add new");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(653, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tpnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAddNew)
                        .addGap(65, 65, 65)
                        .addComponent(btnUpdate)
                        .addGap(66, 66, 66)
                        .addComponent(btnDelete)
                        .addGap(67, 67, 67)
                        .addComponent(btnReset)))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnUpdateStudent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        Student newStudent = new Student();
        // Lay gia tri trong o nhap student number
        newStudent.setStudentNo(txtStudentNo.getText());
        newStudent.setStudentName(txtStudentName.getText());
        
        // Kiem tra gioi tinh Nam hay Nu
        if (rdoMale.isSelected()) {
            newStudent.setGender("Nam");
        } else {
            newStudent.setGender("Nu");
        }
        
        newStudent.setYob(Integer.parseInt(txtYOB.getText()));
        newStudent.setClassName(cboClassName.getSelectedItem().toString());
        newStudent.setNotes(txtNotes.getText());
        newStudent.setStatus(chkStatus.isSelected());
        
        // INSERT NEW STUDENT
        tableModel.addRow(new Object[] {
            newStudent.getStudentNo(), newStudent.getStudentName(),
            newStudent.getGender(), newStudent.getYob(), newStudent.getClassName(),
            newStudent.getFinalGrade(), newStudent.getNotes(), newStudent.isStatus()
        });
        
        JOptionPane.showMessageDialog(this, "Add success");
        
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void tblListStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListStudentMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblListStudent.getSelectedRow();
        txtStudentNo.setText((tableModel.getValueAt(selectedRowIndex, 0)).toString());
        txtStudentName.setText((tableModel.getValueAt(selectedRowIndex, 1)).toString());

        if ((tableModel.getValueAt(selectedRowIndex, 2)).toString().equals("Nam")) {
            rdoMale.setSelected(true);
        } else {
            rdoFemale.setSelected(true);
        }

        txtYOB.setText((tableModel.getValueAt(selectedRowIndex, 3)).toString());
        cboClassName.setSelectedItem((tableModel.getValueAt(selectedRowIndex, 4)).toString());
        txtFinalGrade.setText((tableModel.getValueAt(selectedRowIndex, 5)).toString());
        txtNotes.setText((tableModel.getValueAt(selectedRowIndex, 6)).toString());
        System.out.println(tableModel.getValueAt(selectedRowIndex, 7));
        if (tableModel.getValueAt(selectedRowIndex, 7) != null) {
            chkStatus.setSelected(true);
        } else {
            chkStatus.setSelected(false);
        }

        tpnUpdateStudent.setSelectedIndex(1);
    }//GEN-LAST:event_tblListStudentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Student newStudent = new Student();
        // Lay gia tri trong o nhap student number
        newStudent.setStudentNo(txtStudentNo.getText());
        newStudent.setStudentName(txtStudentName.getText());
        
        // Kiem tra gioi tinh Nam hay Nu
        if (rdoMale.isSelected()) {
            newStudent.setGender("Nam");
        } else {
            newStudent.setGender("Nu");
        }
        
        newStudent.setYob(Integer.parseInt(txtYOB.getText()));
        newStudent.setClassName(cboClassName.getSelectedItem().toString());
        newStudent.setNotes(txtNotes.getText());
        newStudent.setStatus(chkStatus.isSelected());
        
        // UPDATE VALUE
        int selectedRow = tblListStudent.getSelectedRow();
        tableModel.setValueAt(newStudent.getStudentNo(), selectedRow , 0);
        tableModel.setValueAt(newStudent.getStudentName(), selectedRow , 1);
        tableModel.setValueAt(newStudent.getGender(), selectedRow , 2);
        tableModel.setValueAt(newStudent.getYob(), selectedRow , 3);
        tableModel.setValueAt(newStudent.getClassName(), selectedRow , 4);
        tableModel.setValueAt(newStudent.getFinalGrade(), selectedRow , 5);
        tableModel.setValueAt(newStudent.getNotes(), selectedRow , 6);
        tableModel.setValueAt(newStudent.isStatus(), selectedRow , 7);
        
        JOptionPane.showMessageDialog(this, "Update success");
        tpnUpdateStudent.setSelectedIndex(0);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (tblListStudent.getSelectedRow() >= 0) {
            int isConfirm = JOptionPane.showConfirmDialog(this, "Are you sure to delete this record?");
            if (isConfirm == 0) {
                tableModel.removeRow(tblListStudent.getSelectedRow());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboClassName;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pbList;
    private javax.swing.JPanel pnUpdate;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblListStudent;
    private javax.swing.JTabbedPane tpnUpdateStudent;
    private javax.swing.JTextField txtFinalGrade;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentNo;
    private javax.swing.JTextField txtYOB;
    // End of variables declaration//GEN-END:variables
}
