/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java02_cp17308;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUYVU
 */
public class StudentManagement extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    List<Student> listStudent = new ArrayList<>();
    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
        tableModel = (DefaultTableModel) tblListStudent.getModel();
        getComboBoxClassName();
        getDataTable();
    }
    private void getComboBoxClassName(){
        List<String> classNames = new ArrayList<>();
        //b1: tao danh sach
        classNames.add("CP17310");
        classNames.add("CP17308");
        classNames.add("CP17325");
        //b2: them cac phan tu trong danh sach vao comboBoxModel
        for(String name : classNames){
            comboBoxModel.addElement(name);
        }
        //b3: set gia tri model cho cac cboClassName
        cboClassName.setModel(comboBoxModel);
    }
    
    private void getDataTable(){
        //c1
        Student std1 = new Student();
        std1.setStudentNo("PH23123");
        std1.setStudentName("Le Duc Minh");
        std1.setClassName("CP17308");
        std1.setFinalGrade(8);
        std1.setStatus(true);
        
        Student std2 = new Student();
        std2.setStudentNo("PH12703");
        std2.setStudentName("NTKT");
        std2.setClassName("CP17310");
        std2.setFinalGrade(8.5);
        std2.setStatus(true);
        
        listStudent.add(std1);
        listStudent.add(std2);
        
        //c2
        listStudent.add(new Student("PH0001", "NTMT", "Nu", "CP17325", 4, false));
        for (Student std : listStudent){
            // tableModel.addRow(new Object[] {std.});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tpnManageStudent = new javax.swing.JTabbedPane();
        pnList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListStudent = new javax.swing.JTable();
        pnUpdate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cboClassName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFinalGrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkStatus = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Manage Student");

        tblListStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListStudent);

        javax.swing.GroupLayout pnListLayout = new javax.swing.GroupLayout(pnList);
        pnList.setLayout(pnListLayout);
        pnListLayout.setHorizontalGroup(
            pnListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        pnListLayout.setVerticalGroup(
            pnListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tpnManageStudent.addTab("List", pnList);

        jLabel2.setText("Student No");

        jLabel3.setText("Student Name");

        jLabel4.setText("Gender");

        buttonGroup1.add(rdoMale);
        rdoMale.setSelected(true);
        rdoMale.setText("Male");

        buttonGroup1.add(rdoFemale);
        rdoFemale.setText("Female");

        jLabel5.setText("Class Name");

        cboClassName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CP17308", "CP17310", "IT18123", "EC19238" }));

        jLabel6.setText("Finale Grade");

        jLabel7.setText("Status");

        chkStatus.setText("Gradueted ?");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        javax.swing.GroupLayout pnUpdateLayout = new javax.swing.GroupLayout(pnUpdate);
        pnUpdate.setLayout(pnUpdateLayout);
        pnUpdateLayout.setHorizontalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkStatus)
                            .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnUpdateLayout.createSequentialGroup()
                                    .addComponent(rdoMale)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                    .addComponent(rdoFemale))
                                .addComponent(txtStudentNo)
                                .addComponent(txtStudentName)
                                .addComponent(cboClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFinalGrade)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnUpdateLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnReset)
                        .addGap(29, 29, 29))))
        );
        pnUpdateLayout.setVerticalGroup(
            pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUpdateLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoMale)
                    .addComponent(rdoFemale))
                .addGap(34, 34, 34)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFinalGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        tpnManageStudent.addTab("Update", pnUpdate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tpnManageStudent)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Student getValueInput() {
        Student newStudent = new Student();
        newStudent.setStudentNo(txtStudentNo.getText());
        newStudent.setStudentName(txtStudentName.getText());
        
        if (rdoMale.isSelected()) {
            newStudent.setGender("Nam");
        } else {
            newStudent.setGender("Nu");
        }
        newStudent.setClassName(cboClassName.getSelectedItem().toString());
        newStudent.setFinalGrade(Double.parseDouble(txtFinalGrade.getText()));
        newStudent.setStatus(chkStatus.isSelected());
        
        return newStudent;
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Student newStudent = getValueInput();
        
        tableModel.addRow(new Object[] {
            newStudent.getStudentNo(), newStudent.getStudentName(), newStudent.getGender(),
            newStudent.getClassName(), newStudent.getFinalGrade(), newStudent.isStatus()
        });
        
        JOptionPane.showMessageDialog(this, "Insert student successfully!");
        tpnManageStudent.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblListStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListStudentMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblListStudent.getSelectedRow();
        txtStudentNo.setText((tableModel.getValueAt(selectedRowIndex, 0)).toString());
        txtStudentName.setText((tableModel.getValueAt(selectedRowIndex, 1)).toString());
        
        if ((tableModel.getValueAt(selectedRowIndex, 2)).toString().equals("Nam")) {
            rdoMale.setSelected(true);
        } else {
            rdoFemale.setSelected(true);
        }
        
        cboClassName.setSelectedItem((tableModel.getValueAt(selectedRowIndex, 3)).toString());
        txtFinalGrade.setText((tableModel.getValueAt(selectedRowIndex, 4)).toString());
        
        System.out.println(tableModel.getValueAt(selectedRowIndex, 5));
        
        if (tableModel.getValueAt(selectedRowIndex, 5) != null) {
            chkStatus.setSelected(false);
        } else {
            chkStatus.setSelected(true);
        }
        
        tpnManageStudent.setSelectedIndex(1);
    }//GEN-LAST:event_tblListStudentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Student newStudent = getValueInput();
        
        int selectedRowIndex = tblListStudent.getSelectedRow();
        tableModel.setValueAt(newStudent.getStudentNo(), selectedRowIndex , 0);
        tableModel.setValueAt(newStudent.getStudentName(), selectedRowIndex , 1);
        tableModel.setValueAt(newStudent.getGender(), selectedRowIndex , 2);
        tableModel.setValueAt(newStudent.getClassName(), selectedRowIndex , 3);
        tableModel.setValueAt(newStudent.getFinalGrade(), selectedRowIndex , 4);
        tableModel.setValueAt(newStudent.isStatus(), selectedRowIndex , 5);
        
        JOptionPane.showMessageDialog(this, "Update success");

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tblListStudent.getSelectedRow() >= 0){
            int isOk = JOptionPane.showConfirmDialog(this, "Are you sure to delete this record ?");
            if(isOk == 0){
                tableModel.removeRow(tblListStudent.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Delete success");
                
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboClassName;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnList;
    private javax.swing.JPanel pnUpdate;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblListStudent;
    private javax.swing.JTabbedPane tpnManageStudent;
    private javax.swing.JTextField txtFinalGrade;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables
}
